apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: devboard
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: postgres-secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: devboard/postgres
        property: username

    - secretKey: password
      remoteRef:
        key: devboard/postgres
        property: password

    - secretKey: dbname
      remoteRef:
        key: devboard/postgres
        property: dbname
