[devboard]
bastion ansible_host=44.244.138.134

[devboard:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/sam_machine/.ssh/devboard-bastion-new2.pem
ansible_python_interpreter=/usr/bin/python3
